"""s4 media assets

Revision ID: 0de9da1a452c
Revises: 2eaa7f7b18a5
Create Date: 2026-10-05 21:06:18.739308

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0de9da1a452c'
down_revision: str | None = '2eaa7f7b18a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('codec', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_kind'), 'media_assets', ['kind'], unique=False)
    op.create_index(op.f('ix_media_assets_source_id'), 'media_assets', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_assets_source_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_kind'), table_name='media_assets')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
