"""s3 snapshots and discovery runs

Revision ID: 2eaa7f7b18a5
Revises: deaadcfd8d2e
Create Date: 2026-10-05 17:20:44.875041

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2eaa7f7b18a5'
down_revision: str | None = 'deaadcfd8d2e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('units_consumed', sa.Integer(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovery_runs_run_type'), 'discovery_runs', ['run_type'], unique=False)
    op.create_table('source_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_snapshots_source_id'), 'source_snapshots', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_snapshots_source_id'), table_name='source_snapshots')
    op.drop_table('source_snapshots')
    op.drop_index(op.f('ix_discovery_runs_run_type'), table_name='discovery_runs')
    op.drop_table('discovery_runs')
    # ### end Alembic commands ###
