"""s12 rights reviewer and expiry

Revision ID: 5c6fefe72545
Revises: bad99375cae3
Create Date: 2026-10-06 18:56:00.922692

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5c6fefe72545'
down_revision: str | None = 'bad99375cae3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rights_records', sa.Column('reviewer', sa.String(length=128), server_default='', nullable=False))
    op.add_column('rights_records', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rights_records', 'expires_at')
    op.drop_column('rights_records', 'reviewer')
    # ### end Alembic commands ###
