"""s5 transcript audio hash

Revision ID: 695eeee506a4
Revises: 0de9da1a452c
Create Date: 2026-10-05 21:12:50.787911

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '695eeee506a4'
down_revision: str | None = '0de9da1a452c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('audio_sha256', sa.String(length=64), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'audio_sha256')
    # ### end Alembic commands ###
