"""d4 moment features

Revision ID: 83e435e70b31
Revises: e56ee47295f0
Create Date: 2026-10-08 12:09:20.268772

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '83e435e70b31'
down_revision: str | None = 'e56ee47295f0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moments', sa.Column('features_json', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moments', 'features_json')
    # ### end Alembic commands ###
