"""d13 ranker runs

Revision ID: ac3bf805eb17
Revises: decd4fcade07
Create Date: 2026-10-09 22:35:23.518899

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ac3bf805eb17'
down_revision: str | None = 'decd4fcade07'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranker_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('positive', sa.Integer(), nullable=False),
    sa.Column('negative', sa.Integer(), nullable=False),
    sa.Column('new_labels', sa.Integer(), nullable=False),
    sa.Column('holdout_accuracy', sa.Float(), nullable=False),
    sa.Column('holdout_auc', sa.Float(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('weights_path', sa.Text(), nullable=False),
    sa.Column('forced', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ranker_runs')
    # ### end Alembic commands ###
