"""s7 review feedback and moment fields

Revision ID: bad99375cae3
Revises: 695eeee506a4
Create Date: 2026-10-05 21:24:44.624591

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bad99375cae3'
down_revision: str | None = '695eeee506a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moment_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moment_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('original_start', sa.Float(), nullable=False),
    sa.Column('original_end', sa.Float(), nullable=False),
    sa.Column('adjusted_start', sa.Float(), nullable=False),
    sa.Column('adjusted_end', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moment_feedback_decision'), 'moment_feedback', ['decision'], unique=False)
    op.create_index(op.f('ix_moment_feedback_moment_id'), 'moment_feedback', ['moment_id'], unique=False)
    op.add_column('moments', sa.Column('notes', sa.Text(), server_default='', nullable=False))
    op.add_column('moments', sa.Column('category', sa.String(length=64), server_default='', nullable=False))
    op.add_column('moments', sa.Column('is_best', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moments', 'is_best')
    op.drop_column('moments', 'category')
    op.drop_column('moments', 'notes')
    op.drop_index(op.f('ix_moment_feedback_moment_id'), table_name='moment_feedback')
    op.drop_index(op.f('ix_moment_feedback_decision'), table_name='moment_feedback')
    op.drop_table('moment_feedback')
    # ### end Alembic commands ###
