"""s2 init core tables

Revision ID: deaadcfd8d2e
Revises: 
Create Date: 2026-10-05 17:12:31.767330

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'deaadcfd8d2e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=64), nullable=False),
    sa.Column('theme', sa.String(length=128), nullable=False),
    sa.Column('target_duration', sa.Float(), nullable=False),
    sa.Column('actual_duration', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.String(length=128), nullable=False),
    sa.Column('channel_name', sa.String(length=256), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_external_id'), 'sources', ['external_id'], unique=False)
    op.create_table('trend_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('velocity', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('transcript_excerpt', sa.Text(), nullable=False),
    sa.Column('moment_type', sa.String(length=32), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('visual_score', sa.Float(), nullable=False),
    sa.Column('editorial_score', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moments_source_id'), 'moments', ['source_id'], unique=False)
    op.create_table('renders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('codec', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renders_episode_id'), 'renders', ['episode_id'], unique=False)
    op.create_table('rights_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('basis', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('license', sa.String(length=128), nullable=False),
    sa.Column('permission_reference', sa.Text(), nullable=False),
    sa.Column('restrictions', sa.Text(), nullable=False),
    sa.Column('territory', sa.String(length=64), nullable=False),
    sa.Column('commercial_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rights_records_source_id'), 'rights_records', ['source_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('segments_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_source_id'), 'transcripts', ['source_id'], unique=False)
    op.create_table('trend_sources',
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trend_events.id'], ),
    sa.PrimaryKeyConstraint('trend_id', 'source_id')
    )
    op.create_table('episode_segments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('moment_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('transition_type', sa.String(length=32), nullable=False),
    sa.Column('commentary_text', sa.Text(), nullable=False),
    sa.Column('context_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_segments_episode_id'), 'episode_segments', ['episode_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_segments_episode_id'), table_name='episode_segments')
    op.drop_table('episode_segments')
    op.drop_table('trend_sources')
    op.drop_index(op.f('ix_transcripts_source_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_rights_records_source_id'), table_name='rights_records')
    op.drop_table('rights_records')
    op.drop_index(op.f('ix_renders_episode_id'), table_name='renders')
    op.drop_table('renders')
    op.drop_index(op.f('ix_moments_source_id'), table_name='moments')
    op.drop_table('moments')
    op.drop_table('trend_events')
    op.drop_index(op.f('ix_sources_external_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('episodes')
    # ### end Alembic commands ###
