"""d10 scenes

Revision ID: decd4fcade07
Revises: 83e435e70b31
Create Date: 2026-10-09 17:51:45.145169

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'decd4fcade07'
down_revision: str | None = '83e435e70b31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_source_id'), 'scenes', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_source_id'), table_name='scenes')
    op.drop_table('scenes')
    # ### end Alembic commands ###
