"""s13 job next run at

Revision ID: e56ee47295f0
Revises: 5c6fefe72545
Create Date: 2026-10-07 19:44:49.306106

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e56ee47295f0'
down_revision: str | None = '5c6fefe72545'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'next_run_at')
    # ### end Alembic commands ###
